export const EmailTypes = {
    INTERVIEW_REQUEST: 'INTERVIEW_REQUEST',
    INTERVIEW_CONFIRMATION: 'INTERVIEW_CONFIRMATION',
    INTERVIEW_SCHEDULED: 'INTERVIEW_SCHEDULED',
    INTERVIEW_CANCEL: 'INTERVIEW_CANCEL',
    RESET_PASSWORD: 'RESET_PASSWORD'
}